# JM1

set_property PACKAGE_PIN C22  [get_ports HRTIM_CHA1             ]
set_property PACKAGE_PIN H22  [get_ports HRTIM_CHE1             ]
set_property PACKAGE_PIN A22  [get_ports HRTIM_CHA2             ]
set_property PACKAGE_PIN D22  [get_ports HRTIM_CHE2             ]
set_property PACKAGE_PIN G22  [get_ports DI1                    ]
set_property PACKAGE_PIN A18  [get_ports DI0                    ]
set_property PACKAGE_PIN B21  [get_ports LPTIM2_OUT             ]
set_property PACKAGE_PIN D16  [get_ports FP_LED_0               ]
set_property PACKAGE_PIN A21  [get_ports FP_LED_1               ]
set_property PACKAGE_PIN B15  [get_ports FP_LED_2               ]
set_property PACKAGE_PIN A16  [get_ports FP_LED_3               ]
set_property PACKAGE_PIN B17  [get_ports SPI1_MOSI              ]
set_property PACKAGE_PIN B16  [get_ports SPI1_MISO              ]
set_property PACKAGE_PIN E20  [get_ports SPI1_NSS               ]
set_property PACKAGE_PIN B22  [get_ports QSPI_NCS               ]
set_property PACKAGE_PIN G20  [get_ports QSPI_CLK               ]
set_property PACKAGE_PIN G21  [get_ports {QSPI_IO[0]}           ]
set_property PACKAGE_PIN D21  [get_ports {QSPI_IO[1]}           ]
set_property PACKAGE_PIN E21  [get_ports {QSPI_IO[2]}           ]
set_property PACKAGE_PIN B20  [get_ports {QSPI_IO[3]}           ]
set_property PACKAGE_PIN E19  [get_ports SPI1_SCK               ]
set_property PACKAGE_PIN B19  [get_ports CLK_100M               ]
set_property PACKAGE_PIN D18  [get_ports ADC_AUX_DOUTA          ]
set_property PACKAGE_PIN C17  [get_ports ADC_AUX_DOUTB          ]
set_property PACKAGE_PIN C20  [get_ports LED3                   ]
set_property PACKAGE_PIN D20  [get_ports LED2                   ]
set_property PACKAGE_PIN G16  [get_ports LED1                   ]
set_property PACKAGE_PIN F22  [get_ports I2C1_SCL               ]
set_property PACKAGE_PIN C18  [get_ports I2C1_SDA               ]
set_property PACKAGE_PIN G15  [get_ports UART4_TX               ]
set_property PACKAGE_PIN E18  [get_ports DAC_AUX_BIN            ]
set_property PACKAGE_PIN D15  [get_ports ADC_AUX_SGL            ]
set_property PACKAGE_PIN F21  [get_ports ADC_AUX_A0             ]
set_property PACKAGE_PIN G19  [get_ports ADC_AUX_A1             ]
set_property PACKAGE_PIN F19  [get_ports ADC_AUX_A2             ]
set_property PACKAGE_PIN F17  [get_ports DAC_AUX_nCLR           ]
set_property PACKAGE_PIN G17  [get_ports ADC_AUX_RANGE          ]
set_property PACKAGE_PIN E16  [get_ports DAC_AUX_nLDAC          ]
set_property PACKAGE_PIN F16  [get_ports ADC_AUX_SCLK           ]
set_property PACKAGE_PIN C19  [get_ports ADC_AUX_nCS            ]
set_property PACKAGE_PIN H20  [get_ports DAC_AUX_SDIN           ]
set_property PACKAGE_PIN H19  [get_ports DAC_AUX_SDO            ]
set_property PACKAGE_PIN F18  [get_ports DAC_AUX_nSYNC          ]
set_property PACKAGE_PIN E15  [get_ports DAC_AUX_SCLK           ]
set_property PACKAGE_PIN A17  [get_ports ETH_LED1               ]
set_property PACKAGE_PIN A19  [get_ports ETH_LED2               ]
set_property PACKAGE_PIN C15  [get_ports ADC_AFE_CH2_GAIN_X10   ]
set_property PACKAGE_PIN D17  [get_ports ADC_AFE_CH1_GAIN_X10   ]

set_property IOSTANDARD LVCMOS33 [get_ports HRTIM_CHA1          ]      
set_property IOSTANDARD LVCMOS33 [get_ports HRTIM_CHE1          ]      
set_property IOSTANDARD LVCMOS33 [get_ports HRTIM_CHA2          ]      
set_property IOSTANDARD LVCMOS33 [get_ports HRTIM_CHE2          ]      
set_property IOSTANDARD LVCMOS33 [get_ports DI1                 ]      
set_property IOSTANDARD LVCMOS33 [get_ports DI0                 ]      
set_property IOSTANDARD LVCMOS33 [get_ports LPTIM2_OUT          ]      
set_property IOSTANDARD LVCMOS33 [get_ports FP_LED_0            ]      
set_property IOSTANDARD LVCMOS33 [get_ports FP_LED_1            ]      
set_property IOSTANDARD LVCMOS33 [get_ports FP_LED_2            ]      
set_property IOSTANDARD LVCMOS33 [get_ports FP_LED_3            ]      
set_property IOSTANDARD LVCMOS33 [get_ports SPI1_MOSI           ]      
set_property IOSTANDARD LVCMOS33 [get_ports SPI1_MISO           ]      
set_property IOSTANDARD LVCMOS33 [get_ports SPI1_NSS            ]      
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_NCS            ]      
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_CLK            ]      
set_property IOSTANDARD LVCMOS33 [get_ports {QSPI_IO[0]}        ]      
set_property IOSTANDARD LVCMOS33 [get_ports {QSPI_IO[1]}        ]      
set_property IOSTANDARD LVCMOS33 [get_ports {QSPI_IO[2]}        ]      
set_property IOSTANDARD LVCMOS33 [get_ports {QSPI_IO[3]}        ]      
set_property IOSTANDARD LVCMOS33 [get_ports SPI1_SCK            ]      
set_property IOSTANDARD LVCMOS33 [get_ports CLK_100M            ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AUX_DOUTA       ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AUX_DOUTB       ]      
set_property IOSTANDARD LVCMOS33 [get_ports LED3                ]      
set_property IOSTANDARD LVCMOS33 [get_ports LED2                ]      
set_property IOSTANDARD LVCMOS33 [get_ports LED1                ]      
set_property IOSTANDARD LVCMOS33 [get_ports I2C1_SCL            ]      
set_property IOSTANDARD LVCMOS33 [get_ports I2C1_SDA            ]      
set_property IOSTANDARD LVCMOS33 [get_ports UART4_TX            ]      
set_property IOSTANDARD LVCMOS33 [get_ports DAC_AUX_BIN         ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AUX_SGL         ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AUX_A0          ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AUX_A1          ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AUX_A2          ]      
set_property IOSTANDARD LVCMOS33 [get_ports DAC_AUX_nCLR        ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AUX_RANGE       ]      
set_property IOSTANDARD LVCMOS33 [get_ports DAC_AUX_nLDAC       ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AUX_SCLK        ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AUX_nCS         ]      
set_property IOSTANDARD LVCMOS33 [get_ports DAC_AUX_SDIN        ]      
set_property IOSTANDARD LVCMOS33 [get_ports DAC_AUX_SDO         ]      
set_property IOSTANDARD LVCMOS33 [get_ports DAC_AUX_nSYNC       ]      
set_property IOSTANDARD LVCMOS33 [get_ports DAC_AUX_SCLK        ]      
set_property IOSTANDARD LVCMOS33 [get_ports ETH_LED1            ]      
set_property IOSTANDARD LVCMOS33 [get_ports ETH_LED2            ]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AFE_CH2_GAIN_X10]      
set_property IOSTANDARD LVCMOS33 [get_ports ADC_AFE_CH1_GAIN_X10]      

# JM2

set_property PACKAGE_PIN   AA22   [get_ports DAC_nCS            ]
set_property PACKAGE_PIN   W20    [get_ports SI5340_SCL         ]
set_property PACKAGE_PIN   AB22   [get_ports DAC_SDIO           ]
set_property PACKAGE_PIN   W21    [get_ports SI5340_SDA         ]
set_property PACKAGE_PIN   AA21   [get_ports SI5340_LOS_XAXBb   ]
set_property PACKAGE_PIN   AB21   [get_ports Si5340_nLOL        ]
set_property PACKAGE_PIN   W17    [get_ports FPGA_CLK1_CLK_N    ]
set_property PACKAGE_PIN   Y19    [get_ports SI5340_nINTR       ]
set_property PACKAGE_PIN   W18    [get_ports FPGA_CLK1_CLK_P    ]
set_property PACKAGE_PIN   AA19   [get_ports DAC_SCLK           ]
set_property PACKAGE_PIN   W16    [get_ports SI5340_nRST        ]
set_property PACKAGE_PIN   Y18    [get_ports DAC_AFE_CH1_nPD    ]
set_property PACKAGE_PIN   Y16    [get_ports AT_EVENT           ]
set_property PACKAGE_PIN   AA18   [get_ports DAC_AFE_CH2_nPD    ]
set_property PACKAGE_PIN   AA17   [get_ports ADC_CS             ]
set_property PACKAGE_PIN   AB17   [get_ports ADC_SCK            ]
set_property PACKAGE_PIN   AA16   [get_ports ADC_SDI            ]
set_property PACKAGE_PIN   AB16   [get_ports ADC_SDO            ]
                                  
set_property IOSTANDARD  LVCMOS18   [get_ports DAC_nCS          ]
set_property IOSTANDARD  LVCMOS18   [get_ports SI5340_SCL       ] 
set_property IOSTANDARD  LVCMOS18   [get_ports DAC_SDIO         ] 
set_property IOSTANDARD  LVCMOS18   [get_ports SI5340_SDA       ] 
set_property IOSTANDARD  LVCMOS18   [get_ports SI5340_LOS_XAXBb ] 
set_property IOSTANDARD  LVCMOS18   [get_ports Si5340_nLOL      ] 
set_property IOSTANDARD  LVCMOS18   [get_ports FPGA_CLK1_CLK_N  ] 
set_property IOSTANDARD  LVCMOS18   [get_ports SI5340_nINTR     ] 
set_property IOSTANDARD  LVCMOS18   [get_ports FPGA_CLK1_CLK_P  ] 
set_property IOSTANDARD  LVCMOS18   [get_ports DAC_SCLK         ] 
set_property IOSTANDARD  LVCMOS18   [get_ports SI5340_nRST      ] 
set_property IOSTANDARD  LVCMOS18   [get_ports DAC_AFE_CH1_nPD  ] 
set_property IOSTANDARD  LVCMOS18   [get_ports AT_EVENT         ] 
set_property IOSTANDARD  LVCMOS18   [get_ports DAC_AFE_CH2_nPD  ] 
set_property IOSTANDARD  LVCMOS18   [get_ports ADC_CS           ] 
set_property IOSTANDARD  LVCMOS18   [get_ports ADC_SCK          ] 
set_property IOSTANDARD  LVCMOS18   [get_ports ADC_SDI          ] 
set_property IOSTANDARD  LVCMOS18   [get_ports ADC_SDO          ] 
 
set_property PACKAGE_PIN U11  [get_ports OUT1D_N     ]
set_property PACKAGE_PIN U12  [get_ports OUT1D_P     ]
set_property PACKAGE_PIN U10  [get_ports FR_P        ]
set_property PACKAGE_PIN U9   [get_ports FR_N        ]

set_property IOSTANDARD LVDS_25  [get_ports OUT1D_N  ]
set_property IOSTANDARD LVDS_25  [get_ports OUT1D_P  ]
set_property IOSTANDARD LVDS_25  [get_ports FR_P     ]
set_property IOSTANDARD LVDS_25  [get_ports FR_N     ]

set_property PACKAGE_PIN AB9     [get_ports OUT1A_P           ]	
set_property PACKAGE_PIN AB10    [get_ports OUT1A_N           ]
set_property PACKAGE_PIN AB11    [get_ports OUT1B_P           ]
set_property PACKAGE_PIN AA11    [get_ports OUT1B_N           ]
set_property PACKAGE_PIN AB12    [get_ports OUT1C_P           ]
set_property PACKAGE_PIN AA12    [get_ports OUT1C_N           ]
set_property PACKAGE_PIN V10     [get_ports OUT2A_P           ]
set_property PACKAGE_PIN V9      [get_ports OUT2A_N           ]
set_property PACKAGE_PIN Y6      [get_ports OUT2B_P	          ]
set_property PACKAGE_PIN Y5      [get_ports OUT2B_N           ]
set_property PACKAGE_PIN V12     [get_ports OUT2C_P           ]	
set_property PACKAGE_PIN W12     [get_ports OUT2C_N           ]	
set_property PACKAGE_PIN W10     [get_ports OUT2D_N           ]
set_property PACKAGE_PIN W11     [get_ports OUT2D_P           ]
set_property PACKAGE_PIN Y9      [get_ports DCO_P             ]
set_property PACKAGE_PIN Y8      [get_ports DCO_N             ]
set_property PACKAGE_PIN AA8     [get_ports CLK2_P            ]
set_property PACKAGE_PIN AA9     [get_ports CLK2_N            ]
set_property PACKAGE_PIN U4      [get_ports LVDS7_P           ]
set_property PACKAGE_PIN T4      [get_ports LVDS7_N           ]
set_property PACKAGE_PIN AB6     [get_ports LVDS6_P           ]
set_property PACKAGE_PIN AB7     [get_ports LVDS6_N           ]
set_property PACKAGE_PIN AA4     [get_ports LVDS5_P           ]
set_property PACKAGE_PIN Y4      [get_ports LVDS5_N           ]
set_property PACKAGE_PIN AB1     [get_ports LVDS4_P           ]
set_property PACKAGE_PIN AB2     [get_ports LVDS4_N           ]
set_property PACKAGE_PIN W7      [get_ports LVDS3_P           ]
set_property PACKAGE_PIN V7      [get_ports LVDS3_N           ]
set_property PACKAGE_PIN V4      [get_ports LVDS2_P           ]
set_property PACKAGE_PIN V5      [get_ports LVDS2_N           ]
set_property PACKAGE_PIN R6      [get_ports LVDS1_P           ]
set_property PACKAGE_PIN T6      [get_ports LVDS1_N           ]
set_property PACKAGE_PIN AA7     [get_ports LVDS0_P           ]
set_property PACKAGE_PIN AA6     [get_ports LVDS0_N           ]
set_property PACKAGE_PIN U6      [get_ports ADC_AFE_CH2_nSHDN ]
set_property PACKAGE_PIN U5      [get_ports ADC_AFE_CH1_nSHDN ]
set_property PACKAGE_PIN W8      [get_ports TERM_STAT0        ]
set_property PACKAGE_PIN V8      [get_ports TERM_STAT1        ]

				
set_property IOSTANDARD LVDS_25  [get_ports OUT1A_P        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT1A_N        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT1B_P        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT1B_N        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT1C_P        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT1C_N        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT2A_P        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT2A_N        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT2B_N        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT2B_N        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT2C_P        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT2C_N        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT2D_N        ]
set_property IOSTANDARD LVDS_25  [get_ports OUT2D_P        ]

set_property IOSTANDARD LVDS_25  [get_ports DCO_P              ]
set_property IOSTANDARD LVDS_25  [get_ports DCO_N              ]
set_property IOSTANDARD LVDS_25  [get_ports CLK2_P             ]
set_property IOSTANDARD LVDS_25  [get_ports CLK2_N             ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS7_P    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS7_N    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS6_P    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS6_N    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS5_P    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS5_N    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS4_P    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS4_N    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS3_P    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS3_N    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS2_P    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS2_N    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS1_P    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS1_N    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS0_P    ]
set_property IOSTANDARD LVDS_25  [get_ports LVDS0_N    ]
         
set_property IOSTANDARD LVCMOS25 [get_ports ADC_AFE_CH2_nSHDN  ]
set_property IOSTANDARD LVCMOS25 [get_ports ADC_AFE_CH1_nSHDN  ]
set_property IOSTANDARD LVCMOS25 [get_ports TERM_STAT0         ]
set_property IOSTANDARD LVCMOS25 [get_ports TERM_STAT1         ]

set_property PACKAGE_PIN T16 [get_ports {DAC_DATA[12]}  ]
set_property PACKAGE_PIN J21 [get_ports {DAC_DATA[8]}   ]
set_property PACKAGE_PIN T17 [get_ports {DAC_DATA[6]}   ]
set_property PACKAGE_PIN J22 [get_ports {DAC_DATA[13]}  ]
set_property PACKAGE_PIN M21 [get_ports {DAC_DATA[11]}  ]
set_property PACKAGE_PIN J20 [get_ports {DAC_DATA[10]}  ]
set_property PACKAGE_PIN M22 [get_ports {DAC_DATA[5]}   ]
set_property PACKAGE_PIN K21 [get_ports {DAC_DATA[7]}   ]
set_property PACKAGE_PIN R20 [get_ports {DAC_DATA[9]}   ]
set_property PACKAGE_PIN R21 [get_ports {DAC_DATA[4]}   ]
set_property PACKAGE_PIN R18 [get_ports {DAC_DATA[2]}   ]
set_property PACKAGE_PIN T18 [get_ports {DAC_DATA[3]}   ]
set_property PACKAGE_PIN N19 [get_ports {DAC_DATA[1]}   ]
set_property PACKAGE_PIN R19 [get_ports {DAC_DATA[0]}   ]
set_property PACKAGE_PIN N20 [get_ports DAC_DCLKIO      ]
set_property PACKAGE_PIN T19 [get_ports DAC_RESET       ]

set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[12]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[8 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[6 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[13]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[11]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[10]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[5 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[7 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[9 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[4 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[2 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[3 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[1 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_DATA[0 ]}   ]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_DCLKIO       ]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_RESET        ]


set_property DIFF_TERM FALSE [get_ports LVDS7_P]
set_property DIFF_TERM FALSE [get_ports LVDS6_P]
set_property DIFF_TERM FALSE [get_ports LVDS5_P]
set_property DIFF_TERM FALSE [get_ports LVDS4_P]
set_property DIFF_TERM FALSE [get_ports LVDS3_P]
set_property DIFF_TERM FALSE [get_ports LVDS2_P]
set_property DIFF_TERM FALSE [get_ports LVDS1_P]
set_property DIFF_TERM FALSE [get_ports LVDS0_P]
set_property DIFF_TERM FALSE [get_ports OUT1A_P]
set_property DIFF_TERM FALSE [get_ports OUT1B_P]
set_property DIFF_TERM FALSE [get_ports OUT1C_P]
set_property DIFF_TERM FALSE [get_ports OUT2A_P]
set_property DIFF_TERM FALSE [get_ports OUT2C_P]
set_property DIFF_TERM FALSE [get_ports OUT2D_P]
set_property DIFF_TERM FALSE [get_ports DCO_P  ]
set_property DIFF_TERM FALSE [get_ports CLK2_P ]
set_property DIFF_TERM FALSE [get_ports OUT1D_P]
set_property DIFF_TERM FALSE [get_ports FR_P   ]
set_property DIFF_TERM FALSE [get_ports FPGA_CLK1_CLK_P]